### ISSUE TITLE
Typing neg in console gives me an error. Airplane server 1.17.1.

### ISSUE THREAD

**Issue by bierdosenhalter** [JoelGodOfwar/NoEndermanGrief#3]
/neg
> neg
```
[08:10:19 WARN]: Unexpected exception while parsing console command "neg"
org.bukkit.command.CommandException: Unhandled exception executing command 'neg' in plugin NoEndermanGrief v1.14_1.0.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.1.jar:git-Airplane-104]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Airplane-104]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869) ~[patched_1.17.1.jar:git-Airplane-104]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:832) ~[patched_1.17.1.jar:git-Airplane-104]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:531) ~[patched_1.17.1.jar:git-Airplane-104]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:493) ~[patched_1.17.1.jar:git-Airplane-104]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Airplane-104]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Airplane-104]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Airplane-104]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at com.github.joelgodofwar.neg.NoEndermanGrief.onCommand(NoEndermanGrief.java:524) ~[NoEndermanGrief-1.14_1.0.2.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Airplane-104]
        ... 9 more
```

**Comment by JoelGodOfwar** [comment]
That is quite odd, the only way to reach line 524 of the code is if you're a player, which the console is not. For faster support please join my discord https://discord.gg/PXN4bzT
