### ISSUE TITLE
Many Errors cause permission denied

### ISSUE THREAD

**Issue by deREALshocK** [JoelGodOfwar/NoEndermanGrief#7]
First, thanks for this plugin i love it and need it.
i get many errors cause permission denied, how can i fix this?

`[20:17:51] [Server thread/INFO]: [NoEndermanGrief] Enabling NoEndermanGrief v1.14_1.0.7
[20:17:51] [Server thread/INFO]: §e**************************************§r
[20:17:51] [Server thread/INFO]: §aNoEndermanGrief v1.14_1.0.7§r Loading...
[20:17:51] [Server thread/INFO]: This is not a DEV version.
[20:17:51] [Server thread/INFO]: Checking lang files...
[20:17:51] [Server thread/INFO]: Checking config file...
[20:17:51] [Server thread/INFO]: §eNoEndermanGrief§r plugins/NoEndermanGrief/config.yml§r
[20:17:51] [Server thread/INFO]: §eNoEndermanGrief§r config.yml not found, creating!§r
[20:17:51] [Server thread/ERROR]: [NoEndermanGrief] Could not save config.yml to plugins/NoEndermanGrief/config.yml
java.io.FileNotFoundException: plugins/NoEndermanGrief/config.yml (Permission denied)
	at java.io.FileOutputStream.open0(Native Method) ~[?:?]
	at java.io.FileOutputStream.open(FileOutputStream.java:293) ~[?:?]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:235) ~[?:?]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:184) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.saveResource(JavaPlugin.java:208) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at com.github.joelgodofwar.neg.NoEndermanGrief.onEnable(NoEndermanGrief.java:162) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:540) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3806-Spigot-c62f4bd-3b55762]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:454) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3806-Spigot-c62f4bd-3b55762]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3806-Spigot-c62f4bd-3b55762]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3806-Spigot-c62f4bd-3b55762]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3806-Spigot-c62f4bd-3b55762]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3806-Spigot-c62f4bd-3b55762]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3806-Spigot-c62f4bd-3b55762]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:17:51] [Server thread/INFO]: Checking config file version...
[20:17:51] [Server thread/INFO]: Config file version=1.0.0 expected=1.0.6
[20:17:51] [Server thread/WARN]: java.nio.file.NoSuchFileException: plugins/NoEndermanGrief/config.yml
[20:17:51] [Server thread/WARN]: 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
[20:17:51] [Server thread/WARN]: 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
[20:17:51] [Server thread/WARN]: 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[20:17:51] [Server thread/WARN]: 	at java.base/sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:548)
[20:17:51] [Server thread/WARN]: 	at java.base/sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:257)
[20:17:51] [Server thread/WARN]: 	at java.base/java.nio.file.Files.copy(Files.java:1305)
[20:17:51] [Server thread/WARN]: 	at com.github.joelgodofwar.neg.NoEndermanGrief.copyFile_Java7(NoEndermanGrief.java:1700)
[20:17:51] [Server thread/WARN]: 	at com.github.joelgodofwar.neg.NoEndermanGrief.onEnable(NoEndermanGrief.java:173)
[20:17:51] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[20:17:51] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[20:17:51] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[20:17:51] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:540)
[20:17:51] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:454)
[20:17:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589)
[20:17:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414)
[20:17:51] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250)
[20:17:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973)
[20:17:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[20:17:51] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[20:17:51] [Server thread/INFO]: §eNoEndermanGrief§r  1.14_1.0.7§c§l [WARNING] §rCould not load config.yml§r
[20:17:51] [Server thread/WARN]: java.io.FileNotFoundException: plugins/NoEndermanGrief/config.yml (No such file or directory)
[20:17:51] [Server thread/WARN]: 	at java.base/java.io.FileInputStream.open0(Native Method)
[20:17:51] [Server thread/WARN]: 	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
[20:17:51] [Server thread/WARN]: 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
[20:17:51] [Server thread/WARN]: 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:126)
[20:17:51] [Server thread/WARN]: 	at com.github.joelgodofwar.neg.NoEndermanGrief.onEnable(NoEndermanGrief.java:178)
[20:17:51] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[20:17:51] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[20:17:51] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[20:17:51] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:540)
[20:17:51] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:454)
[20:17:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589)
[20:17:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414)
[20:17:51] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250)
[20:17:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973)
[20:17:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[20:17:51] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[20:17:51] [Server thread/ERROR]: [NoEndermanGrief] Could not save config.yml to plugins/NoEndermanGrief/config.yml
java.io.FileNotFoundException: plugins/NoEndermanGrief/config.yml (Permission denied)
	at java.io.FileOutputStream.open0(Native Method) ~[?:?]
	at java.io.FileOutputStream.open(FileOutputStream.java:293) ~[?:?]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:235) ~[?:?]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:184) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.saveResource(JavaPlugin.java:208) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at com.github.joelgodofwar.neg.NoEndermanGrief.onEnable(NoEndermanGrief.java:183) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:540) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3806-Spigot-c62f4bd-3b55762]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:454) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3806-Spigot-c62f4bd-3b55762]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3806-Spigot-c62f4bd-3b55762]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3806-Spigot-c62f4bd-3b55762]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3806-Spigot-c62f4bd-3b55762]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3806-Spigot-c62f4bd-3b55762]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3806-Spigot-c62f4bd-3b55762]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:17:51] [Server thread/INFO]: §eNoEndermanGrief§r  1.14_1.0.7§c§l [WARNING] §rCould not load config.yml§r
[20:17:51] [Server thread/WARN]: java.io.FileNotFoundException: plugins/NoEndermanGrief/config.yml (No such file or directory)
[20:17:51] [Server thread/WARN]: 	at java.base/java.io.FileInputStream.open0(Native Method)
[20:17:51] [Server thread/WARN]: 	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
[20:17:51] [Server thread/WARN]: 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
[20:17:51] [Server thread/WARN]: 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:126)
[20:17:51] [Server thread/WARN]: 	at com.github.joelgodofwar.neg.NoEndermanGrief.onEnable(NoEndermanGrief.java:185)
[20:17:51] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[20:17:51] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[20:17:51] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[20:17:51] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:540)
[20:17:51] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:454)
[20:17:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589)
[20:17:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414)
[20:17:51] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250)
[20:17:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973)
[20:17:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[20:17:51] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[20:17:51] [Server thread/WARN]: java.io.FileNotFoundException: plugins/NoEndermanGrief/old_config.yml (No such file or directory)
[20:17:51] [Server thread/WARN]: 	at java.base/java.io.FileInputStream.open0(Native Method)
[20:17:51] [Server thread/WARN]: 	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
[20:17:51] [Server thread/WARN]: 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
[20:17:51] [Server thread/WARN]: 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:126)
[20:17:51] [Server thread/WARN]: 	at com.github.joelgodofwar.neg.NoEndermanGrief.onEnable(NoEndermanGrief.java:191)
[20:17:51] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[20:17:51] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[20:17:51] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[20:17:51] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:540)
[20:17:51] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:454)
[20:17:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589)
[20:17:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414)
[20:17:51] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250)
[20:17:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973)
[20:17:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[20:17:51] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[20:17:51] [Server thread/INFO]: §eNoEndermanGrief§r  1.14_1.0.7§c§l [WARNING] §rCould not save old settings to config.yml§r
[20:17:51] [Server thread/WARN]: java.io.FileNotFoundException: plugins/NoEndermanGrief/config.yml (Permission denied)
[20:17:51] [Server thread/WARN]: 	at java.base/java.io.FileOutputStream.open0(Native Method)
[20:17:51] [Server thread/WARN]: 	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
[20:17:51] [Server thread/WARN]: 	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
[20:17:51] [Server thread/WARN]: 	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
[20:17:51] [Server thread/WARN]: 	at com.github.joelgodofwar.neg.util.YmlConfiguration.save(YmlConfiguration.java:45)
[20:17:51] [Server thread/WARN]: 	at com.github.joelgodofwar.neg.NoEndermanGrief.onEnable(NoEndermanGrief.java:208)
[20:17:51] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[20:17:51] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[20:17:51] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[20:17:51] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:540)
[20:17:51] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:454)
[20:17:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589)
[20:17:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414)
[20:17:51] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250)
[20:17:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973)
[20:17:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[20:17:51] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[20:17:51] [Server thread/INFO]: §eNoEndermanGrief§r config.yml has been updated§r
[20:17:51] [Server thread/INFO]: §eNoEndermanGrief§r  1.14_1.0.7§c§l [WARNING] §rCould not load config.yml§r
[20:17:51] [Server thread/WARN]: java.io.FileNotFoundException: plugins/NoEndermanGrief/config.yml (No such file or directory)
[20:17:51] [Server thread/WARN]: 	at java.base/java.io.FileInputStream.open0(Native Method)
[20:17:51] [Server thread/WARN]: 	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
[20:17:51] [Server thread/WARN]: 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
[20:17:51] [Server thread/WARN]: 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:126)
[20:17:51] [Server thread/WARN]: 	at com.github.joelgodofwar.neg.NoEndermanGrief.onEnable(NoEndermanGrief.java:218)
[20:17:51] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[20:17:51] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[20:17:51] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[20:17:51] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:540)
[20:17:51] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:454)
[20:17:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589)
[20:17:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414)
[20:17:51] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250)
[20:17:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973)
[20:17:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[20:17:51] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[20:17:51] [Server thread/INFO]: Checking for updates...[m
[20:17:52] [Server thread/WARN]: §ccurrentVersion=1.14_1.0.7
[20:17:52] [Server thread/WARN]: §creleaseVersion=1.14_1.0.7
[20:17:52] [Server thread/WARN]: §cdeveloperVersion=1.14_1.0.7.D2
[20:17:52] [Server thread/INFO]: §eNoEndermanGrief§r *!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*§r
[20:17:52] [Server thread/INFO]: §eNoEndermanGrief§r * Version is up to date!§r
[20:17:52] [Server thread/INFO]: §eNoEndermanGrief§r * Donate: https://ko-fi.com/joelgodofwar§r
[20:17:52] [Server thread/INFO]: §eNoEndermanGrief§r *!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*§r
[20:17:52] [Server thread/WARN]: java.io.FileNotFoundException: plugins/NoEndermanGrief/config.yml (No such file or directory)
[20:17:52] [Server thread/WARN]: 	at java.base/java.io.FileInputStream.open0(Native Method)
[20:17:52] [Server thread/WARN]: 	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
[20:17:52] [Server thread/WARN]: 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
[20:17:52] [Server thread/WARN]: 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:126)
[20:17:52] [Server thread/WARN]: 	at com.github.joelgodofwar.neg.NoEndermanGrief.onEnable(NoEndermanGrief.java:284)
[20:17:52] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[20:17:52] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[20:17:52] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[20:17:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:540)
[20:17:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:454)
[20:17:52] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589)
[20:17:52] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414)
[20:17:52] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250)
[20:17:52] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973)
[20:17:52] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[20:17:52] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[20:17:52] [Server thread/INFO]: §eNoEndermanGrief§r  1.14_1.0.7§c§l [DEBUG] §rlang=en_US§r
[20:17:52] [Server thread/INFO]: §e**************************************§r
[20:17:52] [Server thread/INFO]: §aNoEndermanGrief v1.14_1.0.7§r is §lENABLED§r - Loading took 673 ms.
[20:17:52] [Server thread/INFO]: §e**************************************§r
[20:17:52] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[20:17:52] [Server thread/INFO]: Done (35.480s)! For help, type "help"`

**Comment by deREALshocK** [comment]
ah i fixed it by deleting the cfg folder no errors now
